# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-sieltre-kernel"
BBFILE_PATTERN_meta-sieltre-kernel = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-sieltre-kernel = "6"

LAYERDEPENDS_meta-sieltre-kernel = "core"
LAYERSERIES_COMPAT_meta-sieltre-kernel = "walnascar"
